use_frameworks!
target 'CellAnimatorTest_Tests' do
  pod 'CellAnimatorTest', :path => '../'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if ['CellAnimatorTest'].include? target.name
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '5.0'
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
#        else
#        target.build_configurations.each do |config|
#          config.build_settings['SWIFT_VERSION'] = '4.1'
#          config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
#        end
      end
    end
  end
  
end
